// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#include "Ampel.hpp"
#include "Driver.hpp"
#include <stdbool.h> // required for `consume_event` flag
#include <string.h> // for memset

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Ampel* sm, Ampel_StateId desired_state);

static void ROOT_enter(Ampel* sm);

static void TRAFFICLIGHTGREEN_enter(Ampel* sm);

static void TRAFFICLIGHTGREEN_exit(Ampel* sm);

static void TRAFFICLIGHTGREEN_tick(Ampel* sm);

static void TRAFFICLIGHTSTATERED_enter(Ampel* sm);

static void TRAFFICLIGHTSTATERED_exit(Ampel* sm);

static void TRAFFICLIGHTSTATERED_requestgreen(Ampel* sm);

static void TRAFFICLIGHTSTATERED_schranke(Ampel* sm);

static void TRAFFICLIGHTSTATERED_tick(Ampel* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_enter(Ampel* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_exit(Ampel* sm);

static void TRAFFICLIGHTSTATEREDYELLOW_tick(Ampel* sm);

static void TRAFFICLIGHTYELLOW_enter(Ampel* sm);

static void TRAFFICLIGHTYELLOW_exit(Ampel* sm);

static void TRAFFICLIGHTYELLOW_tick(Ampel* sm);

static void TRAFFICSCHRANKE_enter(Ampel* sm);

static void TRAFFICSCHRANKE_exit(Ampel* sm);

static void TRAFFICSCHRANKE_ampel(Ampel* sm);


// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Ampel_ctor(Ampel* sm)
{
    memset(sm, 0, sizeof(*sm));
}

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Ampel_start(Ampel* sm)
{
    ROOT_enter(sm);
    // ROOT behavior
    // uml: TransitionTo(ROOT.<InitialState>)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `ROOT.<InitialState>`.
        // ROOT.<InitialState> is a pseudo state and cannot have an `enter` trigger.
        
        // ROOT.<InitialState> behavior
        // uml: / { initRedLight(); initYellowLight(); initGreenLight(); } TransitionTo(TrafficLightStateRed)
        {
            // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition). Already at LCA, no exiting required.
            
            // Step 2: Transition action: `initRedLight(); initYellowLight(); initGreenLight();`.
            initRedLight(); initYellowLight(); initGreenLight();
            
            // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
            TRAFFICLIGHTSTATERED_enter(sm);
            
            // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
            return;
        } // end of behavior for ROOT.<InitialState>
    } // end of behavior for ROOT
}

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Ampel_dispatch_event(Ampel* sm, Ampel_EventId event_id)
{
    switch (sm->state_id)
    {
        // STATE: Ampel
        case Ampel_StateId_ROOT:
            // No events handled by this state (or its ancestors).
            break;
        
        // STATE: TrafficLightGreen
        case Ampel_StateId_TRAFFICLIGHTGREEN:
            switch (event_id)
            {
                case Ampel_EventId_TICK: TRAFFICLIGHTGREEN_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightStateRed
        case Ampel_StateId_TRAFFICLIGHTSTATERED:
            switch (event_id)
            {
                case Ampel_EventId_TICK: TRAFFICLIGHTSTATERED_tick(sm); break;
                case Ampel_EventId_REQUESTGREEN: TRAFFICLIGHTSTATERED_requestgreen(sm); break;
                case Ampel_EventId_SCHRANKE: TRAFFICLIGHTSTATERED_schranke(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightStateRedYellow
        case Ampel_StateId_TRAFFICLIGHTSTATEREDYELLOW:
            switch (event_id)
            {
                case Ampel_EventId_TICK: TRAFFICLIGHTSTATEREDYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficLightYellow
        case Ampel_StateId_TRAFFICLIGHTYELLOW:
            switch (event_id)
            {
                case Ampel_EventId_TICK: TRAFFICLIGHTYELLOW_tick(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
        
        // STATE: TrafficSchranke
        case Ampel_StateId_TRAFFICSCHRANKE:
            switch (event_id)
            {
                case Ampel_EventId_AMPEL: TRAFFICSCHRANKE_ampel(sm); break;
                
                default: break; // to avoid "unused enumeration value in switch" warning
            }
            break;
    }
    
}

// This function is used when StateSmith doesn't know what the active leaf state is at
// compile time due to sub states or when multiple states need to be exited.
static void exit_up_to_state_handler(Ampel* sm, Ampel_StateId desired_state)
{
    while (sm->state_id != desired_state)
    {
        switch (sm->state_id)
        {
            case Ampel_StateId_TRAFFICLIGHTGREEN: TRAFFICLIGHTGREEN_exit(sm); break;
            
            case Ampel_StateId_TRAFFICLIGHTSTATERED: TRAFFICLIGHTSTATERED_exit(sm); break;
            
            case Ampel_StateId_TRAFFICLIGHTSTATEREDYELLOW: TRAFFICLIGHTSTATEREDYELLOW_exit(sm); break;
            
            case Ampel_StateId_TRAFFICLIGHTYELLOW: TRAFFICLIGHTYELLOW_exit(sm); break;
            
            case Ampel_StateId_TRAFFICSCHRANKE: TRAFFICSCHRANKE_exit(sm); break;
            
            default: return;  // Just to be safe. Prevents infinite loop if state ID memory is somehow corrupted.
        }
    }
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state ROOT
////////////////////////////////////////////////////////////////////////////////

static void ROOT_enter(Ampel* sm)
{
    sm->state_id = Ampel_StateId_ROOT;
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTGREEN
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTGREEN_enter(Ampel* sm)
{
    sm->state_id = Ampel_StateId_TRAFFICLIGHTGREEN;
    
    // TrafficLightGreen behavior
    // uml: enter / { turnOnGreenLight(); ampelTime = 0; }
    {
        // Step 1: execute action `turnOnGreenLight(); ampelTime = 0;`
        turnOnGreenLight(); ampelTime = 0;
    } // end of behavior for TrafficLightGreen
}

static void TRAFFICLIGHTGREEN_exit(Ampel* sm)
{
    // TrafficLightGreen behavior
    // uml: exit / { turnOffGreenLight(); }
    {
        // Step 1: execute action `turnOffGreenLight();`
        turnOffGreenLight();
    } // end of behavior for TrafficLightGreen
    
    sm->state_id = Ampel_StateId_ROOT;
}

static void TRAFFICLIGHTGREEN_tick(Ampel* sm)
{
    // TrafficLightGreen behavior
    // uml: tick / { ampelTime++; }
    {
        // Step 1: execute action `ampelTime++;`
        ampelTime++;
    } // end of behavior for TrafficLightGreen
    
    // TrafficLightGreen behavior
    // uml: tick [ampelTime > 5000] TransitionTo(TrafficLightYellow)
    if (ampelTime > 5000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTGREEN_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightYellow`.
        TRAFFICLIGHTYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightGreen
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATERED
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATERED_enter(Ampel* sm)
{
    sm->state_id = Ampel_StateId_TRAFFICLIGHTSTATERED;
    
    // TrafficLightStateRed behavior
    // uml: enter / { turnOnRedLight(); ampelTime = 0; }
    {
        // Step 1: execute action `turnOnRedLight(); ampelTime = 0;`
        turnOnRedLight(); ampelTime = 0;
    } // end of behavior for TrafficLightStateRed
}

static void TRAFFICLIGHTSTATERED_exit(Ampel* sm)
{
    // TrafficLightStateRed behavior
    // uml: exit / { turnOffRedLight(); }
    {
        // Step 1: execute action `turnOffRedLight();`
        turnOffRedLight();
    } // end of behavior for TrafficLightStateRed
    
    sm->state_id = Ampel_StateId_ROOT;
}

static void TRAFFICLIGHTSTATERED_requestgreen(Ampel* sm)
{
    // TrafficLightStateRed behavior
    // uml: requestGreen TransitionTo(TrafficLightStateRedYellow)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATERED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRedYellow`.
        TRAFFICLIGHTSTATEREDYELLOW_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}

static void TRAFFICLIGHTSTATERED_schranke(Ampel* sm)
{
    // TrafficLightStateRed behavior
    // uml: schranke TransitionTo(TrafficSchranke)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATERED_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficSchranke`.
        TRAFFICSCHRANKE_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}

static void TRAFFICLIGHTSTATERED_tick(Ampel* sm)
{
    // TrafficLightStateRed behavior
    // uml: tick / { ampelTime++; }
    {
        // Step 1: execute action `ampelTime++;`
        ampelTime++;
    } // end of behavior for TrafficLightStateRed
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTSTATEREDYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTSTATEREDYELLOW_enter(Ampel* sm)
{
    sm->state_id = Ampel_StateId_TRAFFICLIGHTSTATEREDYELLOW;
    
    // TrafficLightStateRedYellow behavior
    // uml: enter / { turnOnRedLight(); turnOnYellowLight(); ampelTime = 0; }
    {
        // Step 1: execute action `turnOnRedLight(); turnOnYellowLight(); ampelTime = 0;`
        turnOnRedLight(); turnOnYellowLight(); ampelTime = 0;
    } // end of behavior for TrafficLightStateRedYellow
}

static void TRAFFICLIGHTSTATEREDYELLOW_exit(Ampel* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: exit / { turnOffRedLight(); turnOffYellowLight(); }
    {
        // Step 1: execute action `turnOffRedLight(); turnOffYellowLight();`
        turnOffRedLight(); turnOffYellowLight();
    } // end of behavior for TrafficLightStateRedYellow
    
    sm->state_id = Ampel_StateId_ROOT;
}

static void TRAFFICLIGHTSTATEREDYELLOW_tick(Ampel* sm)
{
    // TrafficLightStateRedYellow behavior
    // uml: tick / { ampelTime++; }
    {
        // Step 1: execute action `ampelTime++;`
        ampelTime++;
    } // end of behavior for TrafficLightStateRedYellow
    
    // TrafficLightStateRedYellow behavior
    // uml: tick [ampelTime > 2000] TransitionTo(TrafficLightGreen)
    if (ampelTime > 2000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTSTATEREDYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightGreen`.
        TRAFFICLIGHTGREEN_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightStateRedYellow
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICLIGHTYELLOW
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICLIGHTYELLOW_enter(Ampel* sm)
{
    sm->state_id = Ampel_StateId_TRAFFICLIGHTYELLOW;
    
    // TrafficLightYellow behavior
    // uml: enter / { turnOnYellowLight(); ampelTime = 0; }
    {
        // Step 1: execute action `turnOnYellowLight(); ampelTime = 0;`
        turnOnYellowLight(); ampelTime = 0;
    } // end of behavior for TrafficLightYellow
}

static void TRAFFICLIGHTYELLOW_exit(Ampel* sm)
{
    // TrafficLightYellow behavior
    // uml: exit / { turnOffYellowLight(); }
    {
        // Step 1: execute action `turnOffYellowLight();`
        turnOffYellowLight();
    } // end of behavior for TrafficLightYellow
    
    sm->state_id = Ampel_StateId_ROOT;
}

static void TRAFFICLIGHTYELLOW_tick(Ampel* sm)
{
    // TrafficLightYellow behavior
    // uml: tick / { ampelTime++; }
    {
        // Step 1: execute action `ampelTime++;`
        ampelTime++;
    } // end of behavior for TrafficLightYellow
    
    // TrafficLightYellow behavior
    // uml: tick [ampelTime > 3000] TransitionTo(TrafficLightStateRed)
    if (ampelTime > 3000)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICLIGHTYELLOW_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficLightYellow
    
    // No ancestor handles this event.
}


////////////////////////////////////////////////////////////////////////////////
// event handlers for state TRAFFICSCHRANKE
////////////////////////////////////////////////////////////////////////////////

static void TRAFFICSCHRANKE_enter(Ampel* sm)
{
    sm->state_id = Ampel_StateId_TRAFFICSCHRANKE;
    
    // TrafficSchranke behavior
    // uml: enter / { openSchranke(); turnOnRedLight(); }
    {
        // Step 1: execute action `openSchranke(); turnOnRedLight();`
        openSchranke(); turnOnRedLight();
    } // end of behavior for TrafficSchranke
}

static void TRAFFICSCHRANKE_exit(Ampel* sm)
{
    // TrafficSchranke behavior
    // uml: exit / { closeSchranke(); wait();turnOffRedLight(); }
    {
        // Step 1: execute action `closeSchranke(); wait();turnOffRedLight();`
        closeSchranke(); wait();turnOffRedLight();
    } // end of behavior for TrafficSchranke
    
    sm->state_id = Ampel_StateId_ROOT;
}

static void TRAFFICSCHRANKE_ampel(Ampel* sm)
{
    // TrafficSchranke behavior
    // uml: ampel TransitionTo(TrafficLightStateRed)
    {
        // Step 1: Exit states until we reach `ROOT` state (Least Common Ancestor for transition).
        TRAFFICSCHRANKE_exit(sm);
        
        // Step 2: Transition action: ``.
        
        // Step 3: Enter/move towards transition target `TrafficLightStateRed`.
        TRAFFICLIGHTSTATERED_enter(sm);
        
        // Step 4: complete transition. Ends event dispatch. No other behaviors are checked.
        return;
    } // end of behavior for TrafficSchranke
    
    // No ancestor handles this event.
}

// Thread safe.
char const * Ampel_state_id_to_string(Ampel_StateId id)
{
    switch (id)
    {
        case Ampel_StateId_ROOT: return "ROOT";
        case Ampel_StateId_TRAFFICLIGHTGREEN: return "TRAFFICLIGHTGREEN";
        case Ampel_StateId_TRAFFICLIGHTSTATERED: return "TRAFFICLIGHTSTATERED";
        case Ampel_StateId_TRAFFICLIGHTSTATEREDYELLOW: return "TRAFFICLIGHTSTATEREDYELLOW";
        case Ampel_StateId_TRAFFICLIGHTYELLOW: return "TRAFFICLIGHTYELLOW";
        case Ampel_StateId_TRAFFICSCHRANKE: return "TRAFFICSCHRANKE";
        default: return "?";
    }
}

// Thread safe.
char const * Ampel_event_id_to_string(Ampel_EventId id)
{
    switch (id)
    {
        case Ampel_EventId_AMPEL: return "AMPEL";
        case Ampel_EventId_REQUESTGREEN: return "REQUESTGREEN";
        case Ampel_EventId_SCHRANKE: return "SCHRANKE";
        case Ampel_EventId_TICK: return "TICK";
        default: return "?";
    }
}
