// Autogenerated with StateSmith 0.19.0+b5719011215d41a81572ed347c02b22db5d1a48f.
// Algorithm: Balanced2. See https://github.com/StateSmith/StateSmith/wiki/Algorithms

#pragma once  // You can also specify normal include guard. See https://github.com/StateSmith/StateSmith/blob/main/docs/settings.md
#include <stdint.h>

typedef enum Ampel_EventId
{
    Ampel_EventId_AMPEL = 0,
    Ampel_EventId_REQUESTGREEN = 1,
    Ampel_EventId_SCHRANKE = 2,
    Ampel_EventId_TICK = 3
} Ampel_EventId;

enum
{
    Ampel_EventIdCount = 4
};

typedef enum Ampel_StateId
{
    Ampel_StateId_ROOT = 0,
    Ampel_StateId_TRAFFICLIGHTGREEN = 1,
    Ampel_StateId_TRAFFICLIGHTSTATERED = 2,
    Ampel_StateId_TRAFFICLIGHTSTATEREDYELLOW = 3,
    Ampel_StateId_TRAFFICLIGHTYELLOW = 4,
    Ampel_StateId_TRAFFICSCHRANKE = 5
} Ampel_StateId;

enum
{
    Ampel_StateIdCount = 6
};


// Generated state machine
// forward declaration
typedef struct Ampel Ampel;

// State machine constructor. Must be called before start or dispatch event functions. Not thread safe.
void Ampel_ctor(Ampel* sm);

// Starts the state machine. Must be called before dispatching events. Not thread safe.
void Ampel_start(Ampel* sm);

// Dispatches an event to the state machine. Not thread safe.
// Note! This function assumes that the `event_id` parameter is valid.
void Ampel_dispatch_event(Ampel* sm, Ampel_EventId event_id);

// Thread safe.
char const * Ampel_state_id_to_string(Ampel_StateId id);

// Thread safe.
char const * Ampel_event_id_to_string(Ampel_EventId id);

// Generated state machine
struct Ampel
{
    // Used internally by state machine. Feel free to inspect, but don't modify.
    Ampel_StateId state_id;
};

